var json = [ { created_at: 'Mon Feb 27 23:59:56 +0000 2017',
        id: 836365280183902200,
        id_str: '836365280183902208',
        text: 'RT @CharlesMBlow: My daughter is a superhero. That is all… #fencing https://t.co/PoNPDagHFt',
        truncated: false,
        entities:
         { hashtags: [Object],
           symbols: [],
           user_mentions: [Object],
           urls: [],
           media: [Object] },
        extended_entities: { media: [Object] },
        metadata: { iso_language_code: 'en', result_type: 'recent' },
        source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user:
         { id: 2899225470,
           id_str: '2899225470',
           name: 'PorcupineEeyore',
           screen_name: 'PorcupineEeyore',
           location: '',
           description: 'Alter ego of an altered ego...',
           url: null,
           entities: [Object],
           protected: false,
           followers_count: 582,
           friends_count: 1003,
           listed_count: 31,
           created_at: 'Fri Nov 14 10:40:22 +0000 2014',
           favourites_count: 134039,
           utc_offset: null,
           time_zone: null,
           geo_enabled: false,
           verified: false,
           statuses_count: 26542,
           lang: 'en',
           contributors_enabled: false,
           is_translator: false,
           is_translation_enabled: false,
           profile_background_color: 'C0DEED',
           profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
           profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
           profile_background_tile: false,
           profile_image_url: 'http://pbs.twimg.com/profile_images/727195988897632256/3f2w472Q_normal.jpg',
           profile_image_url_https: 'https://pbs.twimg.com/profile_images/727195988897632256/3f2w472Q_normal.jpg',
           profile_link_color: '1DA1F2',
           profile_sidebar_border_color: 'C0DEED',
           profile_sidebar_fill_color: 'DDEEF6',
           profile_text_color: '333333',
           profile_use_background_image: true,
           has_extended_profile: false,
           default_profile: true,
           default_profile_image: false,
           following: null,
           follow_request_sent: null,
           notifications: null,
           translator_type: 'none' },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        retweeted_status:
         { created_at: 'Mon Feb 27 23:51:05 +0000 2017',
           id: 836363054669566000,
           id_str: '836363054669565953',
           text: 'My daughter is a superhero. That is all… #fencing https://t.co/PoNPDagHFt',
           truncated: false,
           entities: [Object],
           extended_entities: [Object],
           metadata: [Object],
           source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
           in_reply_to_status_id: null,
           in_reply_to_status_id_str: null,
           in_reply_to_user_id: null,
           in_reply_to_user_id_str: null,
           in_reply_to_screen_name: null,
           user: [Object],
           geo: null,
           coordinates: null,
           place: null,
           contributors: null,
           is_quote_status: false,
           retweet_count: 269,
           favorite_count: 5286,
           favorited: false,
           retweeted: false,
           possibly_sensitive: false,
           lang: 'en' },
        is_quote_status: false,
        retweet_count: 269,
        favorite_count: 0,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Mon Feb 27 23:59:40 +0000 2017',
        id: 836365212026605600,
        id_str: '836365212026605568',
        text: 'RT @CharlesMBlow: My daughter is a superhero. That is all… #fencing https://t.co/PoNPDagHFt',
        truncated: false,
        entities:
         { hashtags: [Object],
           symbols: [],
           user_mentions: [Object],
           urls: [],
           media: [Object] },
        extended_entities: { media: [Object] },
        metadata: { iso_language_code: 'en', result_type: 'recent' },
        source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user:
         { id: 612627624,
           id_str: '612627624',
           name: 'Adjua Z.M. Adama',
           screen_name: 'Adjua_Adama',
           location: 'Maryland',
           description: 'Teacher, MCPS. Pilot: COMMERCIAL, instrument, single-engine land, multi-engine land. Here We Go Steelers. Proud Penn State Alum.',
           url: null,
           entities: [Object],
           protected: false,
           followers_count: 215,
           friends_count: 730,
           listed_count: 23,
           created_at: 'Tue Jun 19 13:20:55 +0000 2012',
           favourites_count: 6921,
           utc_offset: -28800,
           time_zone: 'Pacific Time (US & Canada)',
           geo_enabled: false,
           verified: false,
           statuses_count: 8444,
           lang: 'en',
           contributors_enabled: false,
           is_translator: false,
           is_translation_enabled: false,
           profile_background_color: '030303',
           profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/719462866/99e0fb9256495033dcb1d7afdd188162.jpeg',
           profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/719462866/99e0fb9256495033dcb1d7afdd188162.jpeg',
           profile_background_tile: false,
           profile_image_url: 'http://pbs.twimg.com/profile_images/823726016044507136/KFiIt-DW_normal.jpg',
           profile_image_url_https: 'https://pbs.twimg.com/profile_images/823726016044507136/KFiIt-DW_normal.jpg',
           profile_banner_url: 'https://pbs.twimg.com/profile_banners/612627624/1487902101',
           profile_link_color: '0084B4',
           profile_sidebar_border_color: 'FFFFFF',
           profile_sidebar_fill_color: 'DDEEF6',
           profile_text_color: '333333',
           profile_use_background_image: true,
           has_extended_profile: true,
           default_profile: false,
           default_profile_image: false,
           following: null,
           follow_request_sent: null,
           notifications: null,
           translator_type: 'none' },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        retweeted_status:
         { created_at: 'Mon Feb 27 23:51:05 +0000 2017',
           id: 836363054669566000,
           id_str: '836363054669565953',
           text: 'My daughter is a superhero. That is all… #fencing https://t.co/PoNPDagHFt',
           truncated: false,
           entities: [Object],
           extended_entities: [Object],
           metadata: [Object],
           source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
           in_reply_to_status_id: null,
           in_reply_to_status_id_str: null,
           in_reply_to_user_id: null,
           in_reply_to_user_id_str: null,
           in_reply_to_screen_name: null,
           user: [Object],
           geo: null,
           coordinates: null,
           place: null,
           contributors: null,
           is_quote_status: false,
           retweet_count: 269,
           favorite_count: 5286,
           favorited: false,
           retweeted: false,
           possibly_sensitive: false,
           lang: 'en' },
        is_quote_status: false,
        retweet_count: 269,
        favorite_count: 0,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Mon Feb 27 23:59:30 +0000 2017',
        id: 836365170360246300,
        id_str: '836365170360246273',
        text: '@xo_superhero_xo \nかすみちゃん誕生日おめでとうございます💙💚💛💜❤💗💖💔💘💕💓🖤❣',
        truncated: false,
        entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
        metadata: { iso_language_code: 'ja', result_type: 'recent' },
        source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: 730269761863438300,
        in_reply_to_user_id_str: '730269761863438338',
        in_reply_to_screen_name: 'xo_superhero_xo',
        user:
         { id: 805359590883721200,
           id_str: '805359590883721217',
           name: '朝 倉 遥 菜',
           screen_name: 'happy__888',
           location: 'フォバないとリムる.',
           description: 'Tomishima.￤15ago. 🌹',
           url: null,
           entities: [Object],
           protected: false,
           followers_count: 422,
           friends_count: 374,
           listed_count: 0,
           created_at: 'Sun Dec 04 10:34:24 +0000 2016',
           favourites_count: 954,
           utc_offset: null,
           time_zone: null,
           geo_enabled: false,
           verified: false,
           statuses_count: 667,
           lang: 'ja',
           contributors_enabled: false,
           is_translator: false,
           is_translation_enabled: false,
           profile_background_color: 'F5F8FA',
           profile_background_image_url: null,
           profile_background_image_url_https: null,
           profile_background_tile: false,
           profile_image_url: 'http://pbs.twimg.com/profile_images/835289250832658433/MsIQI_5d_normal.jpg',
           profile_image_url_https: 'https://pbs.twimg.com/profile_images/835289250832658433/MsIQI_5d_normal.jpg',
           profile_banner_url: 'https://pbs.twimg.com/profile_banners/805359590883721217/1482716809',
           profile_link_color: '1DA1F2',
           profile_sidebar_border_color: 'C0DEED',
           profile_sidebar_fill_color: 'DDEEF6',
           profile_text_color: '333333',
           profile_use_background_image: true,
           has_extended_profile: true,
           default_profile: true,
           default_profile_image: false,
           following: null,
           follow_request_sent: null,
           notifications: null,
           translator_type: 'none' },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 1,
        favorited: false,
        retweeted: false,
        lang: 'ja' },
      { created_at: 'Mon Feb 27 23:59:26 +0000 2017',
        id: 836365155302780900,
        id_str: '836365155302780929',
        text: 'RT @CharlesMBlow: My daughter is a superhero. That is all… #fencing https://t.co/PoNPDagHFt',
        truncated: false,
        entities:
         { hashtags: [Object],
           symbols: [],
           user_mentions: [Object],
           urls: [],
           media: [Object] },
        extended_entities: { media: [Object] },
        metadata: { iso_language_code: 'en', result_type: 'recent' },
        source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user:
         { id: 3419007160,
           id_str: '3419007160',
           name: 'Sonya',
           screen_name: 'suiteplat',
           location: 'Designing Light Switch Covers!',
           description: 'Handcrafted Light Switch Covers for Your Home. Styles for Baby Nursery to Any Room Home Décor. New products are added often! *Wife/Mom/Wine Lover*',
           url: 'https://t.co/rjSI1TSUsV',
           entities: [Object],
           protected: false,
           followers_count: 707,
           friends_count: 1195,
           listed_count: 75,
           created_at: 'Wed Aug 12 22:41:56 +0000 2015',
           favourites_count: 8483,
           utc_offset: -21600,
           time_zone: 'Central Time (US & Canada)',
           geo_enabled: false,
           verified: false,
           statuses_count: 3458,
           lang: 'en',
           contributors_enabled: false,
           is_translator: false,
           is_translation_enabled: false,
           profile_background_color: '000000',
           profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
           profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
           profile_background_tile: false,
           profile_image_url: 'http://pbs.twimg.com/profile_images/835294561668902913/gxzlp3PL_normal.jpg',
           profile_image_url_https: 'https://pbs.twimg.com/profile_images/835294561668902913/gxzlp3PL_normal.jpg',
           profile_banner_url: 'https://pbs.twimg.com/profile_banners/3419007160/1483395534',
           profile_link_color: '981CEB',
           profile_sidebar_border_color: '000000',
           profile_sidebar_fill_color: '000000',
           profile_text_color: '000000',
           profile_use_background_image: false,
           has_extended_profile: false,
           default_profile: false,
           default_profile_image: false,
           following: null,
           follow_request_sent: null,
           notifications: null,
           translator_type: 'none' },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        retweeted_status:
         { created_at: 'Mon Feb 27 23:51:05 +0000 2017',
           id: 836363054669566000,
           id_str: '836363054669565953',
           text: 'My daughter is a superhero. That is all… #fencing https://t.co/PoNPDagHFt',
           truncated: false,
           entities: [Object],
           extended_entities: [Object],
           metadata: [Object],
           source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
           in_reply_to_status_id: null,
           in_reply_to_status_id_str: null,
           in_reply_to_user_id: null,
           in_reply_to_user_id_str: null,
           in_reply_to_screen_name: null,
           user: [Object],
           geo: null,
           coordinates: null,
           place: null,
           contributors: null,
           is_quote_status: false,
           retweet_count: 269,
           favorite_count: 5286,
           favorited: false,
           retweeted: false,
           possibly_sensitive: false,
           lang: 'en' },
        is_quote_status: false,
        retweet_count: 269,
        favorite_count: 0,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Mon Feb 27 23:59:24 +0000 2017',
        id: 836365145433591800,
        id_str: '836365145433591809',
        text: 'I\'m not looking for somebody\nWith some superhuman gifts\nSome superhero\nSome fairytale bliss\nJust something i can turn to\nSomebody i can kiss',
        truncated: false,
        entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
        metadata: { iso_language_code: 'en', result_type: 'recent' },
        source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user:
         { id: 405007052,
           id_str: '405007052',
           name: 'Marta Gonzalez Abad',
           screen_name: 'marta7_gonzalez',
           location: '',
           description: 'Musica 25 horas al dia. Rock. Pianista. Gryffindor.                                      Arnedo(La Rioja)// Alicante // Bilbao\nESPAÑA',
           url: null,
           entities: [Object],
           protected: false,
           followers_count: 289,
           friends_count: 327,
           listed_count: 0,
           created_at: 'Fri Nov 04 18:27:33 +0000 2011',
           favourites_count: 579,
           utc_offset: -36000,
           time_zone: 'Hawaii',
           geo_enabled: false,
           verified: false,
           statuses_count: 1629,
           lang: 'en',
           contributors_enabled: false,
           is_translator: false,
           is_translation_enabled: false,
           profile_background_color: '009AB9',
           profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/731609741/eba1918b9259bdb91f86c55d8709ded9.jpeg',
           profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/731609741/eba1918b9259bdb91f86c55d8709ded9.jpeg',
           profile_background_tile: true,
           profile_image_url: 'http://pbs.twimg.com/profile_images/785252151039787008/cggE_tsH_normal.jpg',
           profile_image_url_https: 'https://pbs.twimg.com/profile_images/785252151039787008/cggE_tsH_normal.jpg',
           profile_banner_url: 'https://pbs.twimg.com/profile_banners/405007052/1445900058',
           profile_link_color: '010D0F',
           profile_sidebar_border_color: 'FFFFFF',
           profile_sidebar_fill_color: 'DDEEF6',
           profile_text_color: '333333',
           profile_use_background_image: true,
           has_extended_profile: true,
           default_profile: false,
           default_profile_image: false,
           following: null,
           follow_request_sent: null,
           notifications: null,
           translator_type: 'none' },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 1,
        favorited: false,
        retweeted: false,
        lang: 'en' },
      { created_at: 'Mon Feb 27 23:59:17 +0000 2017',
        id: 836365115511361500,
        id_str: '836365115511361536',
        text: 'FROZEN ELSA and BABY SPIDERMAN vs JOKER Fun Superhero Magic Show! https://t.co/W9YbsnoNDA @mazetall',
        truncated: false,
        entities:
         { hashtags: [],
           symbols: [],
           user_mentions: [Object],
           urls: [Object] },
        metadata: { iso_language_code: 'en', result_type: 'recent' },
        source: '<a href="http://mazetall.com" rel="nofollow">mazetall_bot</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user:
         { id: 745629461127716900,
           id_str: '745629461127716867',
           name: 'mazetall',
           screen_name: 'mazetall',
           location: 'Web',
           description: 'mazetall(マゼトール)のTwitter公式アカウントです。',
           url: 'https://t.co/B2UNr2e5jM',
           entities: [Object],
           protected: false,
           followers_count: 339,
           friends_count: 245,
           listed_count: 32,
           created_at: 'Wed Jun 22 14:48:11 +0000 2016',
           favourites_count: 0,
           utc_offset: -28800,
           time_zone: 'Pacific Time (US & Canada)',
           geo_enabled: false,
           verified: false,
           statuses_count: 41402,
           lang: 'ja',
           contributors_enabled: false,
           is_translator: false,
           is_translation_enabled: false,
           profile_background_color: 'F5F8FA',
           profile_background_image_url: null,
           profile_background_image_url_https: null,
           profile_background_tile: false,
           profile_image_url: 'http://pbs.twimg.com/profile_images/746683661370564608/-OsFCEDq_normal.jpg',
           profile_image_url_https: 'https://pbs.twimg.com/profile_images/746683661370564608/-OsFCEDq_normal.jpg',
           profile_banner_url: 'https://pbs.twimg.com/profile_banners/745629461127716867/1466858253',
           profile_link_color: '1DA1F2',
           profile_sidebar_border_color: 'C0DEED',
           profile_sidebar_fill_color: 'DDEEF6',
           profile_text_color: '333333',
           profile_use_background_image: true,
           has_extended_profile: false,
           default_profile: true,
           default_profile_image: false,
           following: null,
           follow_request_sent: null,
           notifications: null,
           translator_type: 'none' },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 0,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Mon Feb 27 23:59:05 +0000 2017',
        id: 836365068791070700,
        id_str: '836365068791070721',
        text: 'RT @slinehan1: The couch, the blanket, the giggles and Mon El deciding to become a superhero. These cuties wreck me.\n\nWE LOVE KARAMEL https…',
        truncated: false,
        entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
        metadata: { iso_language_code: 'en', result_type: 'recent' },
        source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user:
         { id: 835622921297150000,
           id_str: '835622921297149956',
           name: 'Neuza Rodrigues',
           screen_name: 'neu_sou_eu',
           location: 'Santa Cruz, Portugal',
           description: 'Portuguese geek, artist and a bit crazy 🙊♌',
           url: null,
           entities: [Object],
           protected: false,
           followers_count: 17,
           friends_count: 51,
           listed_count: 0,
           created_at: 'Sat Feb 25 22:50:04 +0000 2017',
           favourites_count: 480,
           utc_offset: null,
           time_zone: null,
           geo_enabled: false,
           verified: false,
           statuses_count: 469,
           lang: 'pt',
           contributors_enabled: false,
           is_translator: false,
           is_translation_enabled: false,
           profile_background_color: 'F5F8FA',
           profile_background_image_url: null,
           profile_background_image_url_https: null,
           profile_background_tile: false,
           profile_image_url: 'http://pbs.twimg.com/profile_images/835626664268824576/wIDFe7is_normal.jpg',
           profile_image_url_https: 'https://pbs.twimg.com/profile_images/835626664268824576/wIDFe7is_normal.jpg',
           profile_banner_url: 'https://pbs.twimg.com/profile_banners/835622921297149956/1488164249',
           profile_link_color: '1DA1F2',
           profile_sidebar_border_color: 'C0DEED',
           profile_sidebar_fill_color: 'DDEEF6',
           profile_text_color: '333333',
           profile_use_background_image: true,
           has_extended_profile: true,
           default_profile: true,
           default_profile_image: false,
           following: null,
           follow_request_sent: null,
           notifications: null,
           translator_type: 'none' },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        retweeted_status:
         { created_at: 'Mon Feb 27 23:55:53 +0000 2017',
           id: 836364260703862800,
           id_str: '836364260703862784',
           text: 'The couch, the blanket, the giggles and Mon El deciding to become a superhero. These cuties wreck me.\n\nWE LOVE KARA… https://t.co/XOPnTe31vR',
           truncated: true,
           entities: [Object],
           metadata: [Object],
           source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
           in_reply_to_status_id: null,
           in_reply_to_status_id_str: null,
           in_reply_to_user_id: null,
           in_reply_to_user_id_str: null,
           in_reply_to_screen_name: null,
           user: [Object],
           geo: null,
           coordinates: null,
           place: null,
           contributors: null,
           is_quote_status: false,
           retweet_count: 30,
           favorite_count: 41,
           favorited: false,
           retweeted: false,
           possibly_sensitive: false,
           lang: 'en' },
        is_quote_status: false,
        retweet_count: 30,
        favorite_count: 0,
        favorited: false,
        retweeted: false,
        lang: 'en' },
      { created_at: 'Mon Feb 27 23:59:03 +0000 2017',
        id: 836365057076396000,
        id_str: '836365057076396032',
        text: 'RT @slinehan1: The couch, the blanket, the giggles and Mon El deciding to become a superhero. These cuties wreck me.\n\nWE LOVE KARAMEL https…',
        truncated: false,
        entities: { hashtags: [], symbols: [], user_mentions: [Object], urls: [] },
        metadata: { iso_language_code: 'en', result_type: 'recent' },
        source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user:
         { id: 168362551,
           id_str: '168362551',
           name: 'Sofía',
           screen_name: 'SoophieC',
           location: 'Buenos Aires, Argentina',
           description: 'You can never get a cup of tea large enough or a book long enough to suit me. - C.S. Lewis',
           url: null,
           entities: [Object],
           protected: false,
           followers_count: 101,
           friends_count: 92,
           listed_count: 2,
           created_at: 'Mon Jul 19 03:52:36 +0000 2010',
           favourites_count: 14311,
           utc_offset: -10800,
           time_zone: 'Buenos Aires',
           geo_enabled: true,
           verified: false,
           statuses_count: 10797,
           lang: 'es',
           contributors_enabled: false,
           is_translator: false,
           is_translation_enabled: false,
           profile_background_color: 'FFFFFF',
           profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/443155806754590720/gxQpbUjz.png',
           profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/443155806754590720/gxQpbUjz.png',
           profile_background_tile: true,
           profile_image_url: 'http://pbs.twimg.com/profile_images/828729756325642244/pkgOQz36_normal.jpg',
           profile_image_url_https: 'https://pbs.twimg.com/profile_images/828729756325642244/pkgOQz36_normal.jpg',
           profile_banner_url: 'https://pbs.twimg.com/profile_banners/168362551/1479435902',
           profile_link_color: 'AE9BD1',
           profile_sidebar_border_color: 'FFFFFF',
           profile_sidebar_fill_color: 'A8C4C1',
           profile_text_color: '8F9B9D',
           profile_use_background_image: false,
           has_extended_profile: true,
           default_profile: false,
           default_profile_image: false,
           following: null,
           follow_request_sent: null,
           notifications: null,
           translator_type: 'none' },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        retweeted_status:
         { created_at: 'Mon Feb 27 23:55:53 +0000 2017',
           id: 836364260703862800,
           id_str: '836364260703862784',
           text: 'The couch, the blanket, the giggles and Mon El deciding to become a superhero. These cuties wreck me.\n\nWE LOVE KARA… https://t.co/XOPnTe31vR',
           truncated: true,
           entities: [Object],
           metadata: [Object],
           source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
           in_reply_to_status_id: null,
           in_reply_to_status_id_str: null,
           in_reply_to_user_id: null,
           in_reply_to_user_id_str: null,
           in_reply_to_screen_name: null,
           user: [Object],
           geo: null,
           coordinates: null,
           place: null,
           contributors: null,
           is_quote_status: false,
           retweet_count: 30,
           favorite_count: 41,
           favorited: false,
           retweeted: false,
           possibly_sensitive: false,
           lang: 'en' },
        is_quote_status: false,
        retweet_count: 30,
        favorite_count: 0,
        favorited: false,
        retweeted: false,
        lang: 'en' },
      { created_at: 'Mon Feb 27 23:58:59 +0000 2017',
        id: 836365043381973000,
        id_str: '836365043381972992',
        text: 'RT @CharlesMBlow: My daughter is a superhero. That is all… #fencing https://t.co/PoNPDagHFt',
        truncated: false,
        entities:
         { hashtags: [Object],
           symbols: [],
           user_mentions: [Object],
           urls: [],
           media: [Object] },
        extended_entities: { media: [Object] },
        metadata: { iso_language_code: 'en', result_type: 'recent' },
        source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user:
         { id: 1643714730,
           id_str: '1643714730',
           name: 'Joanne',
           screen_name: 'JVT225',
           location: '',
           description: 'Business Development professional, Mom, loves our National Parks, reader',
           url: null,
           entities: [Object],
           protected: false,
           followers_count: 52,
           friends_count: 298,
           listed_count: 5,
           created_at: 'Sat Aug 03 22:03:46 +0000 2013',
           favourites_count: 14,
           utc_offset: null,
           time_zone: null,
           geo_enabled: false,
           verified: false,
           statuses_count: 3786,
           lang: 'en',
           contributors_enabled: false,
           is_translator: false,
           is_translation_enabled: false,
           profile_background_color: 'C0DEED',
           profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
           profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
           profile_background_tile: false,
           profile_image_url: 'http://pbs.twimg.com/profile_images/378800000237057332/58cdb28e7bc35833669a3ef8b8472908_normal.jpeg',
           profile_image_url_https: 'https://pbs.twimg.com/profile_images/378800000237057332/58cdb28e7bc35833669a3ef8b8472908_normal.jpeg',
           profile_link_color: '1DA1F2',
           profile_sidebar_border_color: 'C0DEED',
           profile_sidebar_fill_color: 'DDEEF6',
           profile_text_color: '333333',
           profile_use_background_image: true,
           has_extended_profile: false,
           default_profile: true,
           default_profile_image: false,
           following: null,
           follow_request_sent: null,
           notifications: null,
           translator_type: 'none' },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        retweeted_status:
         { created_at: 'Mon Feb 27 23:51:05 +0000 2017',
           id: 836363054669566000,
           id_str: '836363054669565953',
           text: 'My daughter is a superhero. That is all… #fencing https://t.co/PoNPDagHFt',
           truncated: false,
           entities: [Object],
           extended_entities: [Object],
           metadata: [Object],
           source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
           in_reply_to_status_id: null,
           in_reply_to_status_id_str: null,
           in_reply_to_user_id: null,
           in_reply_to_user_id_str: null,
           in_reply_to_screen_name: null,
           user: [Object],
           geo: null,
           coordinates: null,
           place: null,
           contributors: null,
           is_quote_status: false,
           retweet_count: 269,
           favorite_count: 5286,
           favorited: false,
           retweeted: false,
           possibly_sensitive: false,
           lang: 'en' },
        is_quote_status: false,
        retweet_count: 269,
        favorite_count: 0,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Mon Feb 27 23:58:57 +0000 2017',
        id: 836365032287981600,
        id_str: '836365032287981569',
        text: 'RT @CharlesMBlow: My daughter is a superhero. That is all… #fencing https://t.co/PoNPDagHFt',
        truncated: false,
        entities:
         { hashtags: [Object],
           symbols: [],
           user_mentions: [Object],
           urls: [],
           media: [Object] },
        extended_entities: { media: [Object] },
        metadata: { iso_language_code: 'en', result_type: 'recent' },
        source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user:
         { id: 269129768,
           id_str: '269129768',
           name: 'Bethy Orero',
           screen_name: 'modernmamalogue',
           location: 'Nairobi. Silicon valley, CA',
           description: 'Kenyan transplant in Silicon Valley. Working on Getting to ZERO HIV. Crossfit mama of two. Chronic retweeter',
           url: null,
           entities: [Object],
           protected: false,
           followers_count: 364,
           friends_count: 749,
           listed_count: 30,
           created_at: 'Sun Mar 20 04:37:00 +0000 2011',
           favourites_count: 1151,
           utc_offset: -28800,
           time_zone: 'Pacific Time (US & Canada)',
           geo_enabled: true,
           verified: false,
           statuses_count: 14589,
           lang: 'en',
           contributors_enabled: false,
           is_translator: false,
           is_translation_enabled: false,
           profile_background_color: 'C0DEED',
           profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
           profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
           profile_background_tile: false,
           profile_image_url: 'http://pbs.twimg.com/profile_images/821883077458657280/FPNnUHBI_normal.jpg',
           profile_image_url_https: 'https://pbs.twimg.com/profile_images/821883077458657280/FPNnUHBI_normal.jpg',
           profile_banner_url: 'https://pbs.twimg.com/profile_banners/269129768/1436337708',
           profile_link_color: '1DA1F2',
           profile_sidebar_border_color: 'C0DEED',
           profile_sidebar_fill_color: 'DDEEF6',
           profile_text_color: '333333',
           profile_use_background_image: true,
           has_extended_profile: false,
           default_profile: true,
           default_profile_image: false,
           following: null,
           follow_request_sent: null,
           notifications: null,
           translator_type: 'none' },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        retweeted_status:
         { created_at: 'Mon Feb 27 23:51:05 +0000 2017',
           id: 836363054669566000,
           id_str: '836363054669565953',
           text: 'My daughter is a superhero. That is all… #fencing https://t.co/PoNPDagHFt',
           truncated: false,
           entities: [Object],
           extended_entities: [Object],
           metadata: [Object],
           source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
           in_reply_to_status_id: null,
           in_reply_to_status_id_str: null,
           in_reply_to_user_id: null,
           in_reply_to_user_id_str: null,
           in_reply_to_screen_name: null,
           user: [Object],
           geo: null,
           coordinates: null,
           place: null,
           contributors: null,
           is_quote_status: false,
           retweet_count: 269,
           favorite_count: 5286,
           favorited: false,
           retweeted: false,
           possibly_sensitive: false,
           lang: 'en' },
        is_quote_status: false,
        retweet_count: 269,
        favorite_count: 0,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' } ];


var getData = (function(json){
  console.log(json)
  var dataArray = [];
  for (i=0;i<json.length;i++){dataArray.push(json[i].created_at)}

  return {dataArray:dataArray}

})(json);
